-- ~/.config/hypr/hyprland.lua
-- ============================================================================
-- Modular Hyprland Lua config (0.55+).
-- Each require() is its own error-isolated scope, so a typo in one module
-- won't take down the rest of your session.
-- Reference: https://wiki.hypr.land/Configuring/Start/
-- ============================================================================

-- Safety net: make sure bare-name require() resolves files in THIS folder,
-- regardless of how Hyprland sets up the Lua search path. Wrapped in pcall so
-- that, if the path is locked down, we silently fall back to Hyprland's own
-- require resolution (which already supports sibling files) instead of erroring.
pcall(function()
    local cfg = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "") .. "/.config")
    package.path = cfg .. "/hypr/?.lua;" .. package.path
end)

-- Load order matters a little: theme is pulled in by the modules that need it.
require("monitors")     -- displays
require("looknfeel")    -- general / decoration / layout  (uses theme.lua)
require("animations")   -- curves + animation timings
require("input")        -- keyboard / touchpad / gestures
require("autostart")    -- things to launch once at session start
require("keybinds")     -- all keybindings
require("windowrules")  -- window + workspace rules

-- Note: we never set `hl.config({ autogenerated = true })`, so there is no
-- yellow "autogenerated config" banner to remove. You're good.
